language: php

env:
  - XDEBUG_MODE=coverage
  - TESTS_SLURP_DBADAPTER_MYSQL_HOST="localhost"

php:
  - '7.2'
  - '7.3'
  - '7.4'

services:
  - mysql

before_script:
  - composer self-update
  - composer install --no-interaction --dev

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls