version: "2"
services:
    schnoop:
        build: .
        volumes:
            - .:/src
        links:
            - mysql
        command: bash
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=schnoop_testing
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes